version: '3'
services:
  volttron:
    hostname: vc2
    image: volttron/volttron
    volumes:
      - ./platform_config2.yml:/platform_config.yml
      - ./configs:/home/volttron/configs
    environment:
      - CONFIG=/home/volttron/configs
      - IGNORE_ENV_CHECK=1
      - LOCAL_USER_ID=1000
  volttron-listener:
    hostname: vc3
    image: volttron/volttron
    volumes:
      - ./platform_config3.yml:/platform_config.yml
      - ./configs:/home/volttron/configs
      #- ./docker-compose2.voltron_home:/home/volttron/.volttron
    environment:
      - CONFIG=/home/volttron/configs
      - IGNORE_ENV_CHECK=1
      - LOCAL_USER_ID=1000
