version: '3'
services:
  volttron:
    hostname: vc
    image: volttron/volttron
    ports:
       - 23916:22916
       - 8080:8080
      #- 8443:8443
      #- 6671:5671    # ampqs port
      #- 25671:15671  # management port
    volumes:
      - ./platform_config.yml:/platform_config.yml
      - ./configs:/home/volttron/configs
    environment:
      - CONFIG=/home/volttron/configs
      - IGNORE_ENV_CHECK=1
      - LOCAL_USER_ID=1000

#- LOCAL_USER_ID=1000
