# Properties to be added to the root config file
# the properties should be ingestible for volttron
# the values will be presented in the config file
# as key=value
config:
  vip-address: tcp://0.0.0.0:22916
  # For rabbitmq this should match the hostname specified in
  # in the docker compose file hostname field for the service.
  bind-web-address: http://0.0.0.0:8080
  #volttron-central-address: https://vc:8443
  instance-name: foobar
  message-bus: zmq
  # volttron-central-address: a different address
  # volttron-central-serverkey: a different key

#rabbitmq-config: $CONFIG/rabbitmq_config.yml

# Agents dictionary to install.  The key must be a valid
# identity for the agent to be installed correctly.
agents:

  # Each agent identity.config file should be in the configs
  # directory and will be used to install the agent.
  listener:
    source: $VOLTTRON_ROOT/examples/ListenerAgent
    config: $CONFIG/listener.config # This is an empty element $CONFIG/listener.config

  volttron.central:
    source: $VOLTTRON_ROOT/services/core/VolttronCentral
    config: $VOLTTRON_ROOT/services/core/VolttronCentral/config

  master.driver:
    source: $VOLTTRON_ROOT/services/core/MasterDriverAgent

  platform.agent:
    source: $VOLTTRON_ROOT/services/core/VolttronCentralPlatform
    config: $VOLTTRON_ROOT/services/core/VolttronCentralPlatform/config

  historian:
    source: $VOLTTRON_ROOT/services/core/SQLHistorian
    config: $CONFIG/historian.config

#  platform.actuator:
#    source: $VOLTTRON_ROOT/services/core/ActuatorAgent
#
#  weather:
#    source: $VOLTTRON_ROOT/examples/DataPublisher
#    config: $CONFIG/weather.config

#  price:
#    source: $VOLTTRON_ROOT/examples/DataPublisher
#    config: $CONFIG/price.config

#  platform.bacnet_proxy:
#    source: $VOLTTRON_ROOT/services/core/BACnetProxy
#    config: $CONFIG/bacnet-proxy.json
#  platform.driver:
#    source: $VOLTTRON_ROOT/services/core/MasterDriverAgent
#    config_store:
#      fake.csv:
#        file: $CONFIG/bacnet_example_config.csv
#        type: --csv
#      devices/PNNL/ANNEX:
#        file: $CONFIG/annex.config

